#!/bin/sh

# This is a version of the RazorRun script intended to work with
# HTCondor and not read any files from AFS.  
# Note: the RazorRunAuxFiles tarball contains all auxiliary files
# needed to run jobs for the 2016 MoriondRereco; if you want this
# script to work for other run eras, you'll need to 
# modify it to accept the tarball name as a command line argument.

if [ "$1" == "" ] || [ "$2" == "" ]; then
    echo "RazorRun <list of input files> <analyzer name> <options>"
else
    # This tarball contains all needed files for 2016_MoriondRereco 
    # inclusive razor analysis
    tar vxzf RazorRunAuxFiles_Expanded.tar.gz
    tar vxzf JEC_Summer16_23Sep2016V3.tgz
    tar vxzf Spring16_FastSimV1.tgz

    ./Run$2 $1 ${@:3}
fi
