gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT50to100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/Run2016B-07Aug17
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/Run2016C-07Aug17
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/Run2016D-07Aug17
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/Run2016E-07Aug17
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/Run2016F-07Aug17
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/Run2016G-07Aug17
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/Run2016H-07Aug17
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/TTJets_SingleLeptFromTbar_genMET-150_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-1200To2500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-2500ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-600To800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-70To100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/WJetsToLNu_HT-800To1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/ZJetsToNuNu_HT-100To200_13TeV-madgraph
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/ZJetsToNuNu_HT-1200To2500_13TeV-madgraph
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/ZJetsToNuNu_HT-200To400_13TeV-madgraph
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/ZJetsToNuNu_HT-2500ToInf_13TeV-madgraph
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/ZJetsToNuNu_HT-400To600_13TeV-madgraph
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/ZJetsToNuNu_HT-600To800_13TeV-madgraph
gfal-rm -r gsiftp://transfer.ultralight.org//store/group/phys_exotica/jmao/susy_llp/llp_analyzer/ZJetsToNuNu_HT-800To1200_13TeV-madgraph

