#!/bin/sh
#script for tuning razor analysis cuts
signal="Signals/RazorInclusive_PHYS14_20150819_SMS-T1bbbb_2J_mGl-1500_mLSP-100_20bx25_1pb_weighted.root"
if [ -f limitLoopOutput.txt ]; then
    rm limitLoopOutput.txt
fi
touch limitLoopOutput.txt
#for cut in 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120 125 130 135 140 145 150 #jet pt
#for cut in 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120 125 130 135 140 145 150 #transverse mass
for cut in 2.5 2.525 2.55 2.575 2.6 2.625 2.65 2.675 2.7 2.725 2.75 2.775 2.8 2.825 2.85 2.875 2.9 2.925 2.95 2.975 3.0 3.025 3.05 3.075 3.1 3.125 3.15 #deltaPhi
do
    echo -n $cut" " >> limitLoopOutput.txt
    python python/DustinTuples2DataCard.py -c config/run2_1-3btag.config -d Datasets -b SixJet --dphi-cut $cut Backgrounds/*.root $signal
    #cd Datasets; combineCards.py RazorInclusive_Histograms_lumi-3.0_1-3btag_SixJet.txt RazorInclusive_Histograms_lumi-3.0_1-3btag_FourJet.txt > combined.txt; cd -
    OUTPUT="$(combine -M Asymptotic Datasets/combined.txt | tail -n 8)"
    #OUTPUT="$(combine -M Asymptotic Datasets/RazorInclusive_Histograms_lumi-3.0_1-3btag_SixJet.txt | tail -n 8)"
    echo "${OUTPUT}" | grep "50.0" | awk '{print $5}' >> limitLoopOutput.txt
done
