#!/bin/sh
#usage: SusyFastsimSkim <list file> <gluino mass> <LSP mass>

cat $1 | sed s#root://eoscms//## > tmp.txt
mkdir smstmp
./SkimNtuple tmp.txt smstmp "$2_$3" 'Sum$(sqrt(gParticleE*gParticleE - (gParticlePt*cosh(gParticleEta))*(gParticlePt*cosh(gParticleEta))) > '$2'-0.001 && sqrt(gParticleE*gParticleE - (gParticlePt*cosh(gParticleEta))*(gParticlePt*cosh(gParticleEta))) < '$2'+0.001 && gParticleId == 1000021) > 0 && Sum$(sqrt(gParticleE*gParticleE - (gParticlePt*cosh(gParticleEta))*(gParticlePt*cosh(gParticleEta))) > '$3'-0.001 && sqrt(gParticleE*gParticleE - (gParticlePt*cosh(gParticleEta))*(gParticlePt*cosh(gParticleEta))) < '$3'+0.001 && gParticleId == 1000022) > 0'
hadd -f SMS_$2_$3.root smstmp/*.root 
rm smstmp/*.root
rmdir smstmp
rm tmp.txt
